version: '2'
services:
  prometheus:
    container_name: mon-prometheus
    user: root
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    links:
      - blackbox_exporter
      - alertmanager
    volumes:
      - "./config:/config"
      - "./data/prometheus:/data"
    command:
      - '--config.file=/config/prometheus.yml'
      - '--storage.tsdb.path=/data'
      - '--storage.tsdb.retention=5000h'
  blackbox_exporter:
    container_name: mon-blackbox_exporter
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    dns: 8.8.8.8
    restart: always
    ports:
      - "9115:9115"
    volumes:
      - "./config:/config"
    command: --config.file=/config/blackbox.yml
  alertmanager:
    container_name: mon-alertmanager
    image: prom/alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - "./data/alertmanager:/data"
      - "./config:/config"
    command: --config.file=/config/alertmanager.yml --storage.path=/data
